### PR TITLE
Parse port until the end or to an @ symbol

### PR DESCRIPTION
**Pull request by badboy**
Newer Redis Cluster includes the bus port in the output of `CLUSTER NODES`,
appened to the default ip:port tuple after an @ symbol.

Reference: https://github.com/antirez/redis/commit/b841f3ad1

### CODE REVIEW

**Comment by doyoubi** [comment]
Thanks for helping us with the compability problem.
We are testing the current version of corvus in one of our IDC and going to release 0.2.6 after we are done. Sorry to say that for stability considerations this modification may not be merged into 0.2.6 but next version.
We will merge this after testing.

**Comment by badboy** [comment]
Fully understand not merging in a bug fix release that doesn't officially support Redis >3 anyway. Happy to help out for future compatibility

**Comment by doyoubi** [comment]
We will finally merge this when the [modification of CLUSTER NODES](https://github.com/antirez/redis/issues/2527#issuecomment-210557940) in redis is merged into redis 3.2.

**Comment by doyoubi** [comment]
Now the redis 4 has been released with the new format of `CLUSTER NODES`. I'm going to merge this to keep compatible with the new redis version.

**Pull request merged**
