### PR TITLE
fix EXPIRE cmd access

### PR DESCRIPTION
**Pull request by kols**

### CODE REVIEW

**Comment by kols** [comment]
@maralla

**Comment by doyoubi** [comment]
Thanks for your pull request!

**Comment by wooparadog** [comment]
@doyoubi, @kols is an ex-colleague. Nice to see familiar faces around here.

**Comment by kols** [comment]
Background: the problem came up when we used `read-slave-only` read strategy and then saw a flood of slot update jobs kick off, as every `EXPIRE` command triggered a `MOVED` response from the slave redis node.
Glad to help. And nice to see you too! @wooparadog

**Pull request merged**
